# iperf3 TCP service definition
apiVersion: v1
kind: Service
metadata:
  name: iperf-server-svc
spec:
  selector:
    app: iperf-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: server-tcp
    name: svc-server-tcp
  - protocol: UDP
    port: 5201
    targetPort: server-udp
    name: svc-server-udp

---
# iperf3 UDP service definition
# apiVersion: v1
# kind: Service
# metadata:
#   name: iperf-server-udp
# spec:
#   selector:
#     app: iperf-server
#   ports:
#   

# ---
# iperf3 server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      nodeSelector:
        node: k8s2
      containers:
      - name: iperf-server
        image: vesso/perftest
        args: ['-s']
        ports:
        - containerPort: 5201
          name: server-udp
          protocol: UDP
        - containerPort: 5201
          name: server-tcp
          protocol: TCP
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 0

---
# iperf3 client deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      nodeSelector:
        node: k8s3
      containers:
      - name: iperf-client
        image: vesso/perftest
        command: ['/bin/sh', '-c', 'sleep infinity']
        ports:
        - containerPort: 5201
          name: client
        securityContext:
          capabilities:
            add: ["NET_RAW"]
        imagePullPolicy: IfNotPresent
      terminationGracePeriodSeconds: 0