# iperf3 service definition
# apiVersion: v1
# kind: Service
# metadata:
#   name: iperf-server
# spec:
#   selector:
#     app: iperf-server
#   ports:
#   - port: 5201
#     targetPort: 5201

# ---
# iperf3 server deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-server
  template:
    metadata:
      labels:
        app: iperf-server
    spec:
      nodeSelector:
        node: k8s3
      containers:
      - name: iperf-server
        image: nicolaka/netshoot
        args: ['iperf3', '-s']
        ports:
        - containerPort: 5201
          name: server
      terminationGracePeriodSeconds: 0

---
# iperf3 client deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf-client
  template:
    metadata:
      labels:
        app: iperf-client
    spec:
      nodeSelector:
        node: k8s2
      containers:
      - name: iperf-client
        image: nicolaka/netshoot
        command: ['/bin/sh', '-c', 'sleep infinity']
        ports:
        - containerPort: 5201
          name: client
      terminationGracePeriodSeconds: 0